# configure datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://testhost:3306/mp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '#Dsf135246'

# configure logging
logging:
  level:
    root: warn
    com.jeff.mp.pagination.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  mapper-locations: [ 'classpath:/mapper/*Mapper.xml' ]
