# Configure data source
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://testhost:3306/mp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '#Dsf135246'

# Configure log
logging:
  level:
    root: warn
    com.jeff.mp.ar.dao: trace
  pattern:
    console: '%p%m%n'


mybatis-plus:
  mapper-locations: [ 'classpath:/mapper/*Mapper.xml' ]


  #configuration and config-location cannot be specified at the same time, All attributes in
  #configuration can be configured in the mybatis configuration file
  # config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true

  type-aliases-package: com.jeff.mp.ar.entity

  global-config:
    db-config:
      #ID_WORKER is the default global primary key strategy
      id-type: ID_WORKER

      #NOT_NULL: By default, when the entity class field is null, it is not introduced to where
      #IGNORED: When the entity class field is null, it is still introduced to where, that is, where field=null
      #NOT_EMPTY: When the entity class field is null or an empty string, do not introduce to where
      insert-strategy: NOT_NULL
      updateStrategy: NOT_NULL
      select-strategy: NOT_NULL

      #Table prefix + entity class name (camel case to underscore) = table to operate
      #table-prefix: mp_



