# configure datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://testhost:3306/mp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '#Dsf135246'

# logging
logging:
  level:
    root: warn
    com.jeff.mp.annotation.dao: trace
  pattern:
    console: '%p%m%n'

# global configuration for mybatis plus
mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
      insert-strategy: not_null
      update-strategy: not_null

